apiVersion: v1
kind: Service
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  selector:
    app: backend-feed
  ports:
    - protocol: TCP
      name: "8080"
      port: 8080
      targetPort: 8080