apiVersion: v1
kind: Service
metadata:
  name: frontend
  labesl:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      name: "8180"
      port: 8100
      targetPort: 80